
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xnpfnhuhbjaeuveeaagk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhucGZuaHVoYmphZXV2ZWVhYWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwMTg0MzQsImV4cCI6MjA1NTU5NDQzNH0.qV9g1jucLtU4WkZXPzREsnmNvNGZnK7yOcOqqRTmEdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// If using a PWA, you can request notification permission
export const requestNotificationPermission = async () => {
  if ('Notification' in window) {
    try {
      const permission = await Notification.requestPermission();
      return permission === 'granted';
    } catch (error) {
      console.error('Error requesting notification permission:', error);
      return false;
    }
  }
  return false;
};

// Helper to detect if running as a Progressive Web App (PWA)
export const isPWA = () => {
  return window.matchMedia('(display-mode: standalone)').matches || 
         // Use a type check for iOS standalone mode
         (navigator as any).standalone === true || 
         document.referrer.includes('android-app://');
};
